common:
  databaseFile: loot.db
  feedFilePrefix: lootscraper
  logFile: lootscraper-%DATE%
  logLevel: INFO

browser:
  timeoutSeconds: 30
  headless: false
  loadImages: false

actions:
  scrapeOffers: true
  scrapeInfo: false
  generateFeed: true
  uploadToFtp: false
  telegramBot: false
  discordBot: false

scraper:
  enabledScrapers:
    - AmazonGames
    - SteamGames
  infoSources: []

igdb:
  clientId: ""
  clientSecret: ""

feed:
  authorName: "LootScraper"
  authorEmail: "mail@example.com"
  authorWeb: "https://ajsarcade.github.io/lootscraper"
  urlPrefix: "https://ajsarcade.github.io/lootscraper/"
  urlAlternate: "https://ajsarcade.github.io/lootscraper"
  idPrefix: "https://ajsarcade.github.io/lootscraper/"

ftp:
  host: ""
  user: ""
  password: ""

telegram:
  accessToken: ""
  botOwnerUserId: 0
  botLogChatId: 0
  logLevel: ERROR
  dropPendingMessages: false

discord:
  botToken: ""
  guildId: ""
  adminRoleId: ""
  channelPrefix: ""
  categoryName: "Free Games"
